### ISSUE TITLE
react and react-dom should be moved to peer dependencies

### ISSUE THREAD

**Issue by moubi** [moubi/enform#6]

**Comment by srdjan** [comment]
you'll get rid of ~60% in size - will be the smallest, useful form lib 

https://bundlephobia.com/result?p=enform@2.0.0

**Comment by moubi** [comment]
Nice side effect of start doing things properly I guess 😮 

I also run `yarn size` to check the size of the component after transpilation (`/lib/index.js`) and it says `1.34 kB`. That's very small, but may be it needs more features like at least basic validation  (email, length, type).

**Comment by srdjan** [comment]
there are advantages in keeping it small... you can use https://github.com/ai/size-limit#readme
to keep it low... 
validation can be an external function/predicate (written by the user of the lib), 
and enform just executes it?

**Comment by moubi** [comment]
Yes, that is the idea of enform so far - it gives back validation in users hands and simply executes it in the right moment. I am just not sure if it does too little there. 

May be handling basic validation out of the box❓ Something like:
```jsx
<Enform 
  initial={ email: "" }
  validation={
    email: { type: "email" }
  }
/>
```
Targeting common form use cases as a goal.

**Comment by srdjan** [comment]
yeah, but maybe as a separate, optional package? keeping the core small...
something like:

import { isValidEmail } from '@enform/validation-utils';

**Comment by moubi** [comment]
That's also an idea. I'll post on reddit for feedback on that.
